# Training

In [28]:
import gymnasium as gym
import numpy as np

In [29]:
a=0.8 #learning rate
g=0.95 #discount factor

rng=np.random.default_rng() #random number generator

env=gym.make(
    'FrozenLake-v1',
    desc=None,
    map_name="4x4",
    is_slippery=False,
    reward_schedule=(10,-5,0),
)

def select_action(Q,S,e):
    x=rng.random()
    if x<e:
        return rng.integers(low=0,high=4)
    else:
        return Q[S].argmax()

Q=np.random.randn(64).reshape((16,4)) #make a arbitrary Q table and store it as a 16x4 array
Q[15]=[0,0,0,0]
print("Initial Q table:",Q)

state,info=env.reset()
run=True
n=0

while n<10000:
    while run:
        e=max(0.01,0.999**n) # eps_start=1, eps_end=0.01, eps_decay=0.999, epsilon = max(eps_end, eps_start*(eps_decay)**(episode_number))
        action = select_action(Q,state,e)
        prev_state=state
        state, reward, terminated, truncated, info = env.step(action)
        q=Q[state].max()
        Q[prev_state][action]+=a*(reward+g*q-Q[prev_state][action]) # Q learning implementation

        if truncated or terminated:
            state, info=env.reset()
            run=False
    n+=1
    run=True

print("Final Q table:",(Q))
env.close()

Initial Q table: [[ 1.73087527  1.1134803   0.76905258 -0.27245608]
 [-0.16015009  0.78864344 -0.20740835 -1.31232541]
 [ 0.54777602  0.71036199  1.93092591  1.63196934]
 [ 0.22362559  0.93106984 -2.18750291 -0.78349026]
 [-0.94251364  0.559862   -0.1445933   1.80095235]
 [-1.16240211  1.73046564  0.10144775 -1.2242588 ]
 [ 0.4949491  -1.50333057  1.55972992  2.397711  ]
 [-0.93242636 -0.58221982 -0.46783698 -0.59821223]
 [-0.06934199 -1.14026275  0.11596209  0.34536699]
 [ 0.13533587  0.61510364 -1.40728686  2.3032154 ]
 [-1.83891698  0.25674212 -0.43181042  1.14431698]
 [ 1.17882461 -0.03382959  1.28403042  0.52752311]
 [ 0.58821213  0.03364813  1.20812984 -1.03461862]
 [ 0.33463111 -0.41578877 -0.33699471  0.07411752]
 [ 0.62614173 -1.06670212 -1.17428194 -1.35778512]
 [ 0.          0.          0.          0.        ]]
Final Q table: [[ 7.35091891  7.73780937  7.73780937  7.35091891]
 [ 7.35091891 -3.35605764  8.1450625   7.73780937]
 [ 7.73780937  8.57375     7.73780937  8.1450625 

# Testing

In [30]:
env1=gym.make(
    'FrozenLake-v1',
    desc=None,
    map_name="4x4",
    is_slippery=False,
    reward_schedule=(10, -5, 0),
    render_mode="human"
)

run=True
state, info=env1.reset()
while run:
    action =  Q[state].argmax()
    state, reward, terminated, truncated, info = env1.step(action)

    if truncated or terminated:
        state, info=env1.reset()
        run=False
env1.close()