# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros

In [63]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [64]:
arr2=np.ones(10)
print(arr2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [65]:
arr3=np.full((10),5)
print(arr3)

[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50

In [66]:
arr4=np.arange(10,51,1)
print(arr4)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [67]:
even_arr4=np.arange(10,51,2)
print(even_arr4)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [69]:
arr5=np.random.randint(0,9,(3,3))
print(arr5)

[[7 8 7]
 [0 6 8]
 [6 0 3]]


#### Create a 3x3 identity matrix

In [70]:
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [71]:
x=np.random.rand(1)
print(x)

[0.72019819]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [72]:
y=np.random.rand(25)
print(y)

[0.19074794 0.51421652 0.12809315 0.51285106 0.0619598  0.30270459
 0.68172411 0.69011772 0.57591601 0.93728936 0.15785287 0.84127594
 0.54958055 0.50663633 0.52450499 0.19381946 0.07293413 0.7496525
 0.94090666 0.8660401  0.97024371 0.88314947 0.66452523 0.93721918
 0.42828619]


#### Create the following matrix:

In [43]:
before=np.arange(0.01,1.01,0.01)
after=before.reshape(10,10)
print(after)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [46]:
first=np.arange(0,1+1/19,1/19)
arr6=first.reshape(20)
print(arr6)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [47]:
arr7=np.arange(1,26,1).reshape(5,5)
print(arr7)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [48]:
arr8=arr7[2:,1:]
print(arr8)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [51]:
print(arr8[1,3])

20


In [58]:
arr9=arr7[0:3,1].reshape(3,1)
print(arr9)

[[ 2]
 [ 7]
 [12]]


In [60]:
arr10=arr7[4,0:]
print(arr10)

[21 22 23 24 25]


In [62]:
arr11=arr7[3:,0:]
print(arr11)

[[16 17 18 19 20]
 [21 22 23 24 25]]


# Great Job!